const routes = {
    home: '/',
    product: '/product/:id',
    about: 'about',
    profile: '/account',
    orders: '/account/orders',
    changepassword: '/account/changepassword',
    addresses: '/account/addresses',
    search: '/search',
    contact: '/contact',
    allproducts: '/product/all',
    top: '/top',
    bottom: '/bottom',
    accessory: '/accessory',
    tshirt: 't-shirt',
    shirt_polo: 'shirt',
    jacket: '/jacket',
    pants: '/pants',
    shorts: '/shorts',
    hoodie: '/hoodie',
    bag: '/bag',
    hat: '/hat',
    others: '/others',
    allsale: '/all-sale',
    cart: '/cart',
    login: '/login',
    register: '/register',
    checkout: '/checkout',
    forgotpassword: '/forgotpassword',
};
export default routes;
